# foo = ['a', 'b', 'c']
#  print(foo[3])      # will this result in an error?


# yes the last index is 2 or -1  so 3 will be out of range
